"""
This type stub file was generated by pyright.
"""

ADDITIONAL_DIACRITICS = ...
def remove_symbols_and_diacritics(s: str, keep=...): # -> str:
    """
    Replace any other markers, symbols, and punctuations with a space,
    and drop any diacritics (category 'Mn' and some manual mappings)
    """
    ...

def remove_symbols(s: str): # -> str:
    """
    Replace any other markers, symbols, punctuations with a space, keeping diacritics
    """
    ...

class BasicTextNormalizer:
    def __init__(self, remove_diacritics: bool = ..., split_letters: bool = ...) -> None:
        ...
    
    def __call__(self, s: str): # -> str:
        ...
    


