"""
This type stub file was generated by pyright.
"""

import hashlib
import io
import os
import urllib
import warnings
import torch
from typing import List, Optional, Union
from tqdm import tqdm
from .audio import load_audio, log_mel_spectrogram, pad_or_trim
from .decoding import DecodingOptions, DecodingResult, decode, detect_language
from .model import ModelDimensions, Whisper
from .transcribe import transcribe
from .version import __version__

_MODELS = ...
_ALIGNMENT_HEADS = ...
def available_models() -> List[str]:
    """Returns the names of available models"""
    ...

def load_model(name: str, device: Optional[Union[str, torch.device]] = ..., download_root: str = ..., in_memory: bool = ...) -> Whisper:
    """
    Load a Whisper ASR model

    Parameters
    ----------
    name : str
        one of the official model names listed by `whisper.available_models()`, or
        path to a model checkpoint containing the model dimensions and the model state_dict.
    device : Union[str, torch.device]
        the PyTorch device to put the model into
    download_root: str
        path to download the model files; by default, it uses "~/.cache/whisper"
    in_memory: bool
        whether to preload the model weights into host memory

    Returns
    -------
    model : Whisper
        The Whisper ASR model instance
    """
    ...

