"""
This type stub file was generated by pyright.
"""

import torch
import triton
import triton.language as tl
from functools import lru_cache

@triton.jit
def dtw_kernel(cost, trace, x, x_stride, cost_stride, trace_stride, N, M, BLOCK_SIZE: tl.constexpr): # -> None:
    ...

@lru_cache(maxsize=None)
def median_kernel(filter_width: int): # -> Callable[..., None]:
    ...

def median_filter_cuda(x: torch.Tensor, filter_width: int): # -> Tensor:
    """Apply a median filter of given width along the last dimension of x"""
    ...

